Week 1 - Lecture 1

In [2]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,1,0],[-1,0,2]])

In [5]:
a+b

array([[2, 3, 3],
       [3, 5, 8]])

In [6]:
a-b

array([[0, 1, 3],
       [5, 5, 4]])

In [8]:
# Performs elementwise multiplication
a*b

array([[ 1,  2,  0],
       [-4,  0, 12]])

In [10]:
# Performs matrix multiplication, should give an error.
np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [14]:
# Let us rectify the error, by redefining b.
b = np.array([[1,2],[4,0],[3,-1]])

In [15]:
# Now we will multiply it.

np.matmul(a,b)

array([[18, -1],
       [42,  2]])

In [16]:
res = np.dot(a,b)
res

array([[18, -1],
       [42,  2]])

In [17]:
det = np.linalg.det(res)
det

78.0

In [19]:
inv = np.linalg.inv(res)
inv

array([[ 0.02564103,  0.01282051],
       [-0.53846154,  0.23076923]])